import type { Layout, LayoutWidget, LvProj } from '../project/types';

function toSnakeCase(s: string): string {
  return s
    .replace(/[^a-zA-Z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
    .toLowerCase() || 'obj';
}

function validCId(s: string): string {
  return toSnakeCase(s).replace(/^[0-9]/, (c) => `_${c}`);
}

/** Assign stable IDs to widgets; returns map of path -> id */
function assignIds(root: LayoutWidget, prefix: string, out: Map<string, string>): void {
  const id = root.id ? validCId(root.id) : `${validCId(root.type)}_${prefix}`;
  const path = prefix || 'root';
  out.set(path, id);

  (root.children ?? []).forEach((c, i) => {
    assignIds(c, `${path}_${i}`, out);
  });
}

/** Map LVGL widget type to create function name */
function lvCreateFunc(type: string): string {
  const t = type.toLowerCase();
  if (t === 'obj' || t === 'object') return 'lv_obj_create';
  if (t === 'btn' || t === 'button') return 'lv_btn_create';
  if (t === 'label') return 'lv_label_create';
  if (t === 'img' || t === 'image') return 'lv_img_create';
  if (t === 'slider') return 'lv_slider_create';
  if (t === 'bar') return 'lv_bar_create';
  if (t === 'switch') return 'lv_switch_create';
  if (t === 'checkbox') return 'lv_checkbox_create';
  if (t === 'dropdown') return 'lv_dropdown_create';
  if (t === 'roller') return 'lv_roller_create';
  if (t === 'textarea') return 'lv_textarea_create';
  if (t === 'canvas') return 'lv_canvas_create';
  if (t === 'arc') return 'lv_arc_create';
  if (t === 'spinner') return 'lv_spinner_create';
  return 'lv_obj_create';
}

/** Emit C code for a widget subtree */
function emitWidget(
  w: LayoutWidget,
  path: string,
  parentVar: string,
  idMap: Map<string, string>,
  indent: string
): string[] {
  const id = idMap.get(path);
  if (!id) return [];
  const varName = `ui_${id}`;
  const createFn = lvCreateFunc(w.type);
  const lines: string[] = [];
  lines.push(`${indent}${varName} = ${createFn}(${parentVar});`);
  (w.children ?? []).forEach((c, i) => {
    lines.push(...emitWidget(c, `${path}_${i}`, varName, idMap, indent));
  });
  return lines;
}

/** Generate ui.h content */
export function generateUiH(layout: Layout, _lvproj: LvProj): string {
  const lines: string[] = [];
  lines.push('/* Generated by LVCraft - do not edit */');
  lines.push('#ifndef UI_H');
  lines.push('#define UI_H');
  lines.push('');
  lines.push('#include "lvgl.h"');
  lines.push('');

  if (layout.root) {
    const idMap = new Map<string, string>();
    assignIds(layout.root, 'root', idMap);
    idMap.forEach((id) => {
      lines.push(`extern lv_obj_t *ui_${id};`);
    });
    lines.push('');
  }

  lines.push('void ui_init(void);');
  lines.push('');
  lines.push('#endif');
  return lines.join('\n');
}

/** Generate ui.c content */
export function generateUiC(layout: Layout, _lvproj: LvProj): string {
  const lines: string[] = [];
  lines.push('/* Generated by LVCraft - do not edit */');
  lines.push('#include "ui.h"');
  lines.push('');

  if (!layout.root) {
    lines.push('void ui_init(void) {');
    lines.push('  /* Empty layout */');
    lines.push('}');
    return lines.join('\n');
  }

  const idMap = new Map<string, string>();
  assignIds(layout.root, 'root', idMap);
  idMap.forEach((id) => {
    lines.push(`lv_obj_t *ui_${id} = NULL;`);
  });
  lines.push('');
  lines.push('void ui_init(void)');
  lines.push('{');
  const body = emitWidget(layout.root, 'root', 'NULL', idMap, '  ');
  lines.push(...body);
  lines.push('}');
  return lines.join('\n');
}
